### ISSUE TITLE
Patch breaks screensharing

### ISSUE THREAD

**Issue by jakecrowley** [vaxerski/ZoomWebcamFix#1]
With the patch installed, i can use OBS-VirtualCam perfectly fine, but screensharing fails to start with error code 105035

**Comment by vaxerski** [comment]
Use default instead of file-patch and it will work. Unpatch the original file before I add a method to do that automatically.

go to search
type %appdata%
navigate to Zoom/bin
delete DllSafeCheck.dll
rename DllsafeCheck.dll.original to DllSafeCheck.dll

(alternatively you can re-install the zoom app)

now while using the app, do not press home, just keep it open in the background. It will detect when you run zoom and do its work automatically for you

**Comment by jakecrowley** [comment]
Thank you, works perfectly!
